// src/lib/components/DecadeSection.svelte
<script lang="ts">
	import { onMount, onDestroy } from 'svelte';
	import { birthYear } from '$lib/stores/birthYear';
	import { getBirthYearHint } from '$lib/stores/birthYear';
	import type { DecadeSection } from '$lib/data/decades';

	export let section: DecadeSection;
	export let chartComponent: any = null;
	export let layout: 'left' | 'right' | 'full' | 'stacked' = 'left';
	export let colorTheme: '1950' | '1970' | '1980' | '1990' | '2000' | '2010' | '2020' = '1950';

	let sectionElement: HTMLElement;
	let isVisible = true;

	$: hint = getBirthYearHint($birthYear, parseInt(section.decade.split('er')[0]));

	onMount(() => {
		// Sections sind sofort sichtbar für Pinning
		isVisible = true;
	});
</script>

<section
	id={section.id}
	class="decade-section"
	class:visible={isVisible}
	class:layout-left={layout === 'left'}
	class:layout-right={layout === 'right'}
	class:layout-full={layout === 'full'}
	class:layout-stacked={layout === 'stacked'}
	class:theme-1950={colorTheme === '1950'}
	class:theme-1970={colorTheme === '1970'}
	class:theme-1980={colorTheme === '1980'}
	class:theme-1990={colorTheme === '1990'}
	class:theme-2000={colorTheme === '2000'}
	class:theme-2010={colorTheme === '2010'}
	class:theme-2020={colorTheme === '2020'}
	data-decade={colorTheme}
	bind:this={sectionElement}
>
	<div class="section-grid">
		<div class="narrative-column">
			<div class="sticky-content">
				<span class="decade-label">{section.decade}</span>
				<h2>{section.title}</h2>
				<h3>{section.subtitle}</h3>

				<div class="narrative-text">
					{#each section.narrative as paragraph}
						<p>{paragraph}</p>
					{/each}
				</div>

				{#if hint}
					<div class="birth-year-hint" role="note">
						<svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor">
							<circle cx="12" cy="12" r="10" stroke-width="2" />
							<path d="M12 16v-4M12 8h.01" stroke-width="2" stroke-linecap="round" />
						</svg>
						<p>{hint}</p>
					</div>
				{/if}
			</div>
		</div>

		<div class="media-column">
			{#if chartComponent}
				<div class="chart-container">
					<p class="chart-explainer">{section.chartExplainer}</p>
					<div class="chart-wrapper">
						<svelte:component this={chartComponent} {section} />
					</div>
				</div>
			{/if}
		</div>
	</div>
</section>

<style lang="scss">
	.decade-section {
		min-height: 100vh;
		position: relative;
		background: #0a0a0a;
		padding: 0;
		will-change: transform;

		&.visible {
			opacity: 1;
		}
	}

	// Alternierende Hintergrundfarben
	.decade-section:nth-child(odd) {
		background: #0f0f0f;
	}

	.decade-section:nth-child(even) {
		background: #050505;
	}

	.section-grid {
		display: grid;
		grid-template-columns: 1fr 1fr;
		gap: 4rem;
		max-width: 1400px;
		margin: 0 auto;
		padding: 2rem;
		min-height: 100vh;
		align-items: center;

		@media (max-width: 1024px) {
			grid-template-columns: 1fr;
			gap: 2rem;
		}
	}

	// Layout Varianten
	.layout-right .section-grid {
		grid-template-columns: 1.2fr 1fr;
		.narrative-column {
			order: 2;
		}
		.media-column {
			order: 1;
		}
	}

	.layout-full .section-grid {
		grid-template-columns: 1fr;
		max-width: 1600px;
		gap: 3rem;
	}

	.layout-stacked .section-grid {
		grid-template-columns: 1fr;
		max-width: 900px;
		gap: 2rem;
		
		.sticky-content {
			max-width: 700px;
			margin: 0 auto;
			text-align: center;
		}
		
		.chart-container {
			margin: 0 auto;
		}
	}

	.layout-full .narrative-column {
		max-width: 600px;
	}

	.narrative-column {
		position: relative;
	}

	.sticky-content {
		padding: 2rem;
		background: rgba(26, 26, 26, 0.8);
		backdrop-filter: blur(10px);
		border-radius: 12px;
		border: 1px solid #2a2a2a;
	}

	.decade-label {
		display: inline-block;
		font-size: 0.875rem;
		font-weight: 600;
		text-transform: uppercase;
		letter-spacing: 0.1em;
		color: #ff6b6b;
		margin-bottom: 1rem;
	}

	h2 {
		font-size: clamp(2rem, 4vw, 3rem);
		margin-bottom: 0.5rem;
	}

	h3 {
		font-size: clamp(1.25rem, 2vw, 1.5rem);
		color: #a0a0a0;
		font-weight: 400;
		margin-bottom: 2rem;
	}

	.narrative-text {
		p {
			font-size: 1.125rem;
			line-height: 1.75;
			margin-bottom: 1.5rem;
			color: #d0d0d0;
		}
	}

	.birth-year-hint {
		display: flex;
		align-items: flex-start;
		gap: 1rem;
		margin-top: 2rem;
		padding: 1rem;
		background: rgba(255, 107, 107, 0.1);
		border-left: 3px solid #ff6b6b;
		border-radius: 4px;

		svg {
			flex-shrink: 0;
			color: #ff6b6b;
			margin-top: 0.25rem;
		}

		p {
			font-size: 1rem;
			color: #ff8787;
			margin: 0;
		}
	}

	.media-column {
		display: flex;
		align-items: center;
		justify-content: center;
	}

	.chart-container {
		width: 100%;
	}

	.chart-explainer {
		font-size: 1.125rem;
		line-height: 1.75;
		color: #d0d0d0;
		margin-bottom: 2rem;
		padding: 1.5rem;
		background: rgba(26, 26, 26, 0.6);
		border-radius: 8px;
		border-left: 4px solid #ff6b6b;
	}

	.chart-wrapper {
		min-height: 400px;
		background: #1a1a1a;
		border-radius: 12px;
		padding: 2rem;
		border: 1px solid #2a2a2a;
	}

	@media (prefers-reduced-motion: reduce) {
		.decade-section {
			opacity: 1;
		}
	}

	@media (max-width: 1024px) {
		.decade-section {
			min-height: auto;
		}
		
		.section-grid {
			padding: 1rem;
			min-height: auto;
		}
	}
</style>

// components/DecadeSection.tsx
'use client';

import { useEffect, useState } from 'react';

import type { DecadeSection as DecadeSectionType } from '@/lib/data/decades';
import { getBirthYearHint, useBirthYear } from '@/lib/context/BirthYearContext';
import ChartWrapper from './ChartWrapper';

interface DecadeSectionProps {
  section: DecadeSectionType;
  layout?: 'left' | 'right' | 'full' | 'stacked';
  colorTheme?: '1950' | '1970' | '1980' | '1990' | '2000' | '2010' | '2020';
}

export function DecadeSection({ section, layout = 'left', colorTheme = '1950' }: DecadeSectionProps) {
  const { birthYear } = useBirthYear();
  const [isVisible, setIsVisible] = useState(true);

  useEffect(() => {
    setIsVisible(true);
  }, []);

  const hint = getBirthYearHint(birthYear, parseInt(section.decade.split('er')[0], 10));

  const bgClass = colorTheme === '1950' || colorTheme === '1980' || colorTheme === '2000' ? 'bg-[#0f0f0f]' : 'bg-[#050505]';

  return (
    <section
      id={section.id}
      data-decade={colorTheme}
      className={`decade-section relative min-h-screen ${bgClass} ${isVisible ? 'opacity-100' : 'opacity-0'}`}
    >
      <div
        className={`section-grid mx-auto grid min-h-screen max-w-[1400px] items-center gap-8 p-8 lg:gap-16 ${
          layout === 'right'
            ? 'lg:grid-cols-[1.2fr_1fr]'
            : layout === 'full' || layout === 'stacked'
              ? 'lg:grid-cols-1'
              : 'lg:grid-cols-2'
        }`}
      >
        <div className={`narrative-column relative ${layout === 'right' ? 'lg:order-2' : ''}`}>
          <div className="sticky-content rounded-xl border border-neutral-800 bg-bg-section/80 p-8 backdrop-blur">
            <span className="mb-4 inline-block text-sm font-semibold uppercase tracking-widest text-accent">
              {section.decade}
            </span>
            <h2 className="mb-2 text-[clamp(2rem,4vw,3rem)] font-bold">{section.title}</h2>
            <h3 className="mb-8 text-[clamp(1.25rem,2vw,1.5rem)] font-normal text-text-secondary">
              {section.subtitle}
            </h3>

            <div className="narrative-text space-y-6">
              {section.narrative.map((paragraph, idx) => (
                <p key={idx} className="text-lg leading-relaxed text-neutral-300">
                  {paragraph}
                </p>
              ))}
            </div>

            {hint && (
              <div
                role="note"
                className="mt-8 flex items-start gap-4 rounded border-l-4 border-accent bg-accent/10 p-4"
              >
                <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" className="mt-1 flex-shrink-0">
                  <circle cx="12" cy="12" r="10" strokeWidth="2" />
                  <path d="M12 16v-4M12 8h.01" strokeWidth="2" strokeLinecap="round" />
                </svg>
                <p className="text-accent-subtle">{hint}</p>
              </div>
            )}
          </div>
        </div>

        <div className={`media-column flex items-center justify-center ${layout === 'right' ? 'lg:order-1' : ''}`}>
          <div className="chart-container w-full">
            <p className="mb-8 rounded-lg border-l-4 border-accent bg-bg-section/60 p-6 text-lg leading-relaxed text-neutral-300">
              {section.chartExplainer}
            </p>
            <div className="chart-wrapper rounded-xl border border-neutral-800 bg-bg-section p-8">
              <ChartWrapper section={section} />
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}

export default DecadeSection;
